### ISSUE TITLE
%matplotlib notebook plots not rendering in VScode

### ISSUE THREAD

**Issue by christinamaher** [seqasim/LFPAnalysis#24]
%matplotlib notebook does not render the plot for omitting bad channels (see lines below) when the notebook's run using VScode. 

```
%matplotlib notebook
fig = mne_data.plot(start=0, duration=120, n_channels=8, scalings=mne_data._data.max()/20)
fig.fake_keypress('a')
```

**Comment by christinamaher** [comment]
Python version 3.8.8... seems to be an issue elsewhere: https://github.com/microsoft/vscode-jupyter/issues/4056

**Comment by manishthilagar** [comment]
If %matplotlib notebook is not rendering the plot, you can try %matplotlib inline instead. This will render the plot as a static image directly in the notebook.

Here's an example of how you could modify your code to use %matplotlib inline:

%matplotlib inline
import matplotlib.pyplot as plt

```
fig = mne_data.plot(start=0, duration=120, n_channels=8, scalings=mne_data._data.max()/20)
plt.show()

fig.canvas.toolbar_visible = False
fig.canvas.header_visible = False
fig.canvas.footer_visible = False
fig.canvas.resizable = False
fig.canvas.window().statusBar().setVisible(False)
```
This should display the plot as a static image and hide the toolbars and status bar to give a cleaner presentation.

**Comment by seqasim** [comment]
We need the notebook backend for interactive plots, like the ones mne uses for plotting data for side-scrolling. Static plots don't solve the problem.

GPT doesn't get this one sadly :)

**Comment by seqasim** [comment]
This seems like an issue with VScode, so closing for now
