### ISSUE TITLE
mni x y z coordinates as float to calculate wm electrode distance

### ISSUE THREAD

**Issue by jli-neuro** [seqasim/LFPAnalysis#34]
```wm_elec_dist = np.linalg.norm(elec_data.loc[wm_elec_ix, ['x', 'y', 'z']].values.astype(float) - elec_loc, axis=1)``` 

in line 250 of LFPAnalysis/lfp_preprocess_utils.py instead of 

```wm_elec_dist = np.linalg.norm(elec_data.loc[wm_elec_ix, ['x', 'y', 'z']].values - elec_loc, axis=1)```

**Comment by seqasim** [comment]
Can you clarify this change should be made? Perhaps with an example of an error?

**Comment by jli-neuro** [comment]
Here is an example of an error "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[185], line 6
      4 elec_name = elec_data.loc[elec_ix, 'Channel'].lower()
      5 # compute the distance to all wm electrodes
----> 6 wm_elec_dist = np.linalg.norm(elec_data.loc[wm_elec_ix, ['mni_x', 'mni_y', 'mni_z']].values - elec_loc, axis=1)
      7 # get the 3 closest wm electrodes
      8 wm_elec_ix_closest = wm_elec_ix[np.argsort(wm_elec_dist)[:4]]

TypeError: unsupported operand type(s) for -: 'str' and 'float'"

Also in the previous line, values were converted to float in elec_loc = elec_data.loc[elec_ix, ['mni_x', 'mni_y', 'mni_z']].values.astype(float)
It would be good to keep the values consistent as float

**Comment by seqasim** [comment]
Fixed in `commit 5a02546`

**Comment by seqasim** [comment]
Fixed with commit [https://github.com/seqasim/LFPAnalysis/commit/5a025464bef65a71c0abfc82e096bd296b75d437](url)
