### ISSUE TITLE
'mne.io' has no attribute 'fif'

### ISSUE THREAD

**Issue by jli-neuro** [seqasim/LFPAnalysis#35]
Bug detected in lfp_preprocess_utils.py detect_IEDs function line 567    elif type(mne_data) == mne.io.fif.raw.Raw 
```
   549 elif type(mne_data) == mne.io.fif.raw.Raw: 
    550     data_type = 'continuous'
    551     n_times = mne_data._data.shape[1]

AttributeError: module 'mne.io' has no attribute 'fif'
```

This can fixed by chaging the line to elif type(mne_data) == mne.io.Raw

**Comment by seqasim** [comment]
Good catch! Though the solution actually requires that I change the line:

`elif type(mne_data) == mne.io.fif.raw.Raw:`

to 

`elif type(mne_data) == mne.io.fiff.raw.Raw:`

Done now in commit [f53ecc6](https://github.com/seqasim/LFPAnalysis/commit/f53ecc6d93f6719959075431a048b2b92477dcec)
