### ISSUE TITLE
Need make_epochs to account for naming differences between mne_data and recon labels

### ISSUE THREAD

**Issue by aliefink** [seqasim/LFPAnalysis#38]
Lfp_preprocess_utils.make_epochs fails if there are typos (i vs l) in the recon labels. This problem is solved for make_mne, just needs to be applied to this function as well.

**Comment by seqasim** [comment]
This shouldn't happen, as the mne ch_names from make_mne utilizes the names from the recon labels, and these names are the ones propagated downstream to make_epochs. Could you provide an example/screenshot?

**Comment by aliefink** [comment]
<img width="1073" alt="Screenshot 2023-04-19 at 11 13 44 PM" src="https://user-images.githubusercontent.com/87388664/233249086-8f5dc1c7-aa4d-4d7a-b42a-5945cd1c79bc.png">

**Comment by aliefink** [comment]
I double checked exactly what the difference is between anode_list and the elec_data within the function and the difference was the electrodes in the spreadsheet that had i's instead of l's. also a problem for lesion electrodes that aren't done for recons. If there are electrodes in the mne.ch_names that aren't in the recon labels, the function doesn't work

**Comment by seqasim** [comment]
Weren't able to reproduce this problem so closing for now but can reopen if need be
