### ISSUE TITLE
Repeated downsampling

### ISSUE THREAD

**Issue by aliefink** [seqasim/LFPAnalysis#45]
Current approach downsamples once at the beginning of preprocessing and again during make_epochs function. Consider removing second downsampling step.

**Comment by seqasim** [comment]
This refers to the following lines in `make_epochs`:

```    
    # Filter and downsample the epochs 
    if downsamp_factor is not None:
        ev_epochs.resample(sfreq=ev_epochs.info['sfreq']/downsamp_factor)
        # rm_baseline_epochs.resample(sfreq=ev_epochs.info['sfreq']/downsamp_factor)
```

I agree that conceptually we probably shouldn't downsample twice. But I want people to have the flexibility to downsample the epochs on the fly without repeating their whole preprocessing if they want to mess around with some analyses. But the downsamp_factor is set to `None` by default
