### ISSUE TITLE
Add `__pycache__/` to `.gitignore`

### ISSUE THREAD

**Issue by shawnrhoads** [seqasim/LFPAnalysis#57]
I recommend adding `__pycache__/` to `.gitignore` so the repo can be used more easily across multiple machines. Then, delete the `__pycache__/*` contents within the Github repo.

It might also be helpful to add a few other Python specific things to ignore. See boilerplate here: https://github.com/github/gitignore/blob/main/Python.gitignore

**Comment by seqasim** [comment]
Done with commit [acfeb0d](https://github.com/seqasim/LFPAnalysis/commit/acfeb0dbcda545b3cb6535285fc1ed101de8056a)

**Comment by shawnrhoads** [comment]
`LFPAnalysis/__pycache__` still exists in the repo

**Comment by shawnrhoads** [comment]
Also add `.ipynb_checkpoints` to .gitignore and remove `scripts/.ipynb_checkpoints`

**Comment by seqasim** [comment]
these have all been removed, and .gitignore amended
