### ISSUE TITLE
Missing custom ROI label excel after pip install

### ISSUE THREAD

**Issue by aliefink** [seqasim/LFPAnalysis#62]
Unable to determine custom ROI label using analysis_utils.select_rois_picks for bipolar re-referenced channels because custom ROI excel (YBA_ROI_labelled.xlsx) is missing from package data following pip install. 
Recommendations:
- Update setup.py to include include_package_data=True
- Save YBA_ROI_labelled data as .csv instead of .xlsx
- Add optional argument to analysis_utils.select_rois_picks to allow individualized custom ROI labels

**Comment by seqasim** [comment]
fixed setup.py and analysis utils to locate YBA_ROI_labelled.xlsx with commit https://github.com/seqasim/LFPAnalysis/commit/b6d110e7d8d7640f48b976b287fd4e702e11b094
